name = "RipQP"
uuid = "1e40b3f8-35eb-4cd8-8edd-3e515bb9de08"
authors = ["Geoffroy Leconte <gleconte50@gmail.com> and contributors"]
version = "0.3.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JSOSolvers = "10dff2fc-5484-5881-a0e0-c90441020f8a"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LLSModels = "39f5bc3e-5160-4bf8-ac48-504fd2534d24"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MatrixMarket = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCOO = "fa32481b-f100-4b48-8dc8-c62f61b13870"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
Krylov = "0.8.1"
LDLFactorizations = "0.8.1"
LLSModels = "0.3"
LinearOperators = "2"
MatrixMarket = "0.3"
NLPModelsModifiers = "0.4, 0.5"
Quadmath = "0.5"
QuadraticModels = "0.7.3"
Requires = "1.1.3"
SolverCore = "0.2.3"
SparseMatricesCOO = "0.1"
TimerOutputs = "0.5"
julia = "1"

[extras]
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "QPSReader"]
